### ISSUE TITLE
Crashes on invalid FTP ip

### ISSUE THREAD

**Issue by DJWassink** [joeartsea/node-red-contrib-ftp#11]
When the server is unreachable the FTP node crashes the whole node-red process, this is quite irritating if the FTP node tries to send a file on boot.

This issue happens on a timeout but also if it is unreachable:

![image](https://user-images.githubusercontent.com/1822404/30240190-1195c7f6-956c-11e7-81c9-be8c02cb8170.png)

![image](https://user-images.githubusercontent.com/1822404/30240199-2f8114a0-956c-11e7-97fd-0e0ea9978328.png)

**Comment by joeartsea** [comment]
@DJWassink Please give me this flow JSON.
