### ISSUE TITLE
Put option not working

### ISSUE THREAD

**Issue by ghost** [joeartsea/node-red-contrib-ftp#16]
Hello, i have been working with this wonderful node but nothing seems to be working. 

I configured the node to use the put function, but all it does is to create an empty file (0.0kb) with the "filename" on the ftp server.

Kindly advice on what to do to resolve this issue

**Comment by joeartsea** [comment]
@snmHammond Please give me this flow JSON.

**Comment by ghost** [comment]
Hi Kojo,

I'm glad you contacted.
Fortunately my partner and I have been able to find a solution.

Thanks and Regards.
Samuel Hammond
