### ISSUE TITLE
How can i use for GET msg.filename

### ISSUE THREAD

**Issue by wesker3650** [joeartsea/node-red-contrib-ftp#18]
i am planning to setup a flow that every min get one file which names yyyymmddhhmmss.dat

like  201907102301.dat 201907102302.dat

i use inject every min and funtion to make the filenames 

how can i pass the filename to ftp get the files

thank you

**Comment by joeartsea** [comment]
The file name can be specified by "msg.filename". 
Dynamically generate file names upstream of flow.
