### ISSUE TITLE
Ftp node remembers the previous files sent

### ISSUE THREAD

**Issue by Kartheek1512** [joeartsea/node-red-contrib-ftp#5]
I am using ftp node to send a different file to a remote server every 10 mins.  Each time i inject a true, it sends the present file along with the previous sent files. This issue gets cleared after clicking the Deploy button but again ftp sends two files at the second inject and three files at the third inject. 

At the input end of the ftp only 1 message goes into the ftp node with filename and local filename. But I get multiple outputs. I attached my code in the mail. Can anyone please help 

Thanks,
kartheek
![capture](https://user-images.githubusercontent.com/9099868/28351550-7fe68b9a-6c05-11e7-9a99-d8d3092a95b4.PNG)

**Comment by joeartsea** [comment]
@Kartheek1512 Please give me this flow JSON.

**Comment by joeartsea** [comment]
@Kartheek1512 Sorry. I found the attached file.

**Comment by Kartheek1512** [comment]
I was able to get correct values after correcting ftp node. . There is a bug in the ftp node. Please follow discussion below. 
https://groups.google.com/forum/#!topic/node-red/pgHT4Y5vY9A

**Comment by juggledad** [comment]
the code change to fix this is as follows, moving line 54 'var conn = new ftp();' to just after line 56 'node.on('input', function (msg) {'

    if (this.ftpConfig) {
      var conn = new ftp();   <<==== this is line 54
      var node = this;
      node.on('input', function (msg) {
        var filename = node.filename || msg.filename || '';
        var localFilename = node.localFilename || msg.localFilename || '';
        this.sendMsg = function (err, result) {

to this location

    if (this.ftpConfig) {
      var node = this;
      node.on('input', function (msg) {
        var conn = new ftp();   <<==== new location of old line 54
        var filename = node.filename || msg.filename || '';
        var localFilename = node.localFilename || msg.localFilename || '';
        this.sendMsg = function (err, result) {

See More from Zen of Mud

**Comment by bluepup** [comment]
Version node-red-contrib-ftp 0.0.2 has the error still.
