### ISSUE TITLE
GET option should show the Local Filename

### ISSUE THREAD

**Issue by juggledad** [joeartsea/node-red-contrib-ftp#6]
The GET option, like the PUT option should be exposing the Local Filename (msg.localFilename). This can be accomplished by editing ftp.html and change lines 133 from:
        } else if (id == 'put') {
to:
        } else if (id == 'put' || id == 'get') {

This will allow a user to specify the name of the file in the node itself.

**Comment by joeartsea** [comment]
Thank you for pointing out. Fixed.
