### ISSUE TITLE
DOCUP - add a 'Usage' section to the README.md

### ISSUE THREAD

**Issue by juggledad** [joeartsea/node-red-contrib-ftp#7]
The following would be helpful if added to the README.md

Usage
----------------
This node will allow you to LIST, GET, PUT and DELETE files on a remote FTP server. The GET and PUT options use msg.filename (the path/name of the file on the remote machine) and msg.localFilename (the path/name of the file on the local machine - i.e. the one running NR). 

The DELETE option only specifies msg.filename (the path/name of the file on the remote machine) 
The LIST option returns an array of the file/folders in the user's default ftp folder, containing
type, name, sticky, rights(an object), acl, owner, group, size and date.

**Comment by joeartsea** [comment]
I added the Usage section to the README. This issue will be closed.
